### ISSUE TITLE
Getting in contact

### ISSUE THREAD

**Issue by nesben** [Psychokiller1888/snipsvelux#1]
Hi, is it possible to get in direct contact (maybe over email) to get support? I'm trying to do this with my KLR 100 as well and it would be nice to get some assistance :)

And I'm also looking at interacting it with my Google Home

**Comment by Psychokiller1888** [comment]
Hi
I'm available on Discord if you want. Join the Snips channel and look for me https://discord.gg/UJywgm5

**Comment by Psychokiller1888** [comment]
New mod available along with script update
https://laurentchervet.wordpress.com/2018/06/21/velux-pcb-hack-done/
